name: wow_shopping
description: Wow Shopping
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  common:
    path: ../common
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  flutter_image: ^4.1.13
  http: ^1.5.0
  json_annotation: 4.9.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.9.1
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  decimal: ^3.2.4
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/icons/
    - assets/images/nav/
    - assets/images/promos/

# run with: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 26
