name: server
description: A server app using the shelf package and Docker.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  common:
    path: ../common
  args: ^2.7.0
  collection: ^1.19.1
  json_annotation: 4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  stack_trace: ^1.12.1

dev_dependencies:
  build_runner: any
  lints: ^6.0.0
  json_serializable: ^6.11.1
  http: ^1.5.0
  test: any
