name: common
description: Common code shared between app and server modules
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.9.2'

dependencies:
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: any
  lints: ^6.0.0
  json_serializable: ^6.11.1
